### Get Nykredit jwt
POST http://localhost:7001/security/oauth2/token
Content-Type:application/x-www-form-urlencoded
Authorization:Basic dGVzdDE6cGFzc3cwcmQ=

grant_type=client_credentials

> scriptAuth.js

### Check ping
GET http://localhost:7001/pmp-component-tests/ping
Authorization: Bearer {{oauth-token}}

### Send get request
GET http://localhost:7001/pmp-component-tests/parameter
X-SAC-Roles: INTERNAL-FULL-ACCESS
Accept: text/plain
Authorization: Bearer {{oauth-token}}
