name: Playwright Tests

env:
  TEST_USER_EMAIL: ${{ secrets.TEST_USER_EMAIL }}
  TEST_USER_PASSWORD: ${{ secrets.TEST_USER_PASSWORD }}

on:
  push:
    paths:
      - 'pmp-client/**'
      - '.github/workflows/playwright.yml'
    branches: [main]
  pull_request:
    paths:
      - pmp-client/**
      - '.github/workflows/playwright.yml'
    branches: [main]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        working-directory: pmp-client
        run: npm ci
      - name: Install Playwright Browsers
        working-directory: pmp-client
        run: npx playwright install --with-deps
      - name: Run Playwright tests
        working-directory: pmp-client
        run: npx playwright test
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: pmp-client/playwright-report/
          retention-days: 30
